### ISSUE TITLE
Getting Error for both auth/google and auth/facebook

### ISSUE THREAD

**Issue by playground** [martijnboland/appoints-api-node#1]
Just downloaded appoints-api-node

both 
localhost:3000/auth/google and localhost:3000/auth/facebook yield
1. That’s an error.

Error: invalid_client

The OAuth client was not found.

**Comment by martijnboland** [comment]
What environment? Windows? Did you clone the repro or downloaded the zip?

**Comment by playground** [comment]
On Mac.
Yes I clone the repo from here.

**Comment by martijnboland** [comment]
I'm afraid, I'm unable to reproduce the issue. What nodejs version are you
on?

**Comment by playground** [comment]
I'm running v6.0.0

**Comment by martijnboland** [comment]
Since the issue is over 2 years old, it makes no sense to keep it open. Please open a new issue if problems persist.
